spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  error:
    include-message: on-param
  port: ${SERVER_PORT}

notification:
  mail:
    host: smtp.gmail.com
    port: 587
    username: <username>
    password: <password>
    protocol: smtp
    java-mail-properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com



allowed-leave-days-to-carry-over: 5
holidays:
  api:
    base:
      url: https://date.nager.at/api/v3/publicholidays/

cron-jobs:
  update:
    holidays: "0 0 0 1 6 *"     # At 00:00 on day-of-month 1 in June.
    paid-leave: "0 0 1 1 1 *"   # At 01:00 on day-of-month 1 in January.
  notify:
    paid-leave:
      left: "0 0 9 1 10,11 *"   # At 09:00 on day-of-month 1 in October and November.
      used: "0 0 8 1 * *"       # At 08:00 on day-of-month 1.


