create sequence initial_project.employee_info_id_seq;

alter sequence initial_project.employee_info_id_seq owner to postgres;

create sequence initial_project.entity_info_id_seq;

alter sequence initial_project.entity_info_id_seq owner to postgres;

create table initial_project.leaves
(
    id         integer generated always as identity
        constraint leaves_pk
            primary key,
    days_leave integer default 20 not null
);

alter table initial_project.leaves
    owner to postgres;

create table initial_project.entity_info
(
    id           integer generated always as identity
        constraint employee_info_pk
            primary key,
    date_created varchar,
    created_by   varchar,
    last_updated varchar,
    updated_by   varchar,
    is_deleted   boolean default false not null
);

alter table initial_project.entity_info
    owner to postgres;

alter sequence initial_project.employee_info_id_seq owned by entity_info.id;

alter sequence initial_project.entity_info_id_seq owned by entity_info.id;

create table initial_project.types
(
    id             integer generated by default as identity
        constraint types_pk
            primary key,
    type_name      varchar,
    days_leave     integer default 20 not null,
    entity_info_id integer
        constraint types_entity_info_id_fk
            references entity_info
);

alter table initial_project.types
    owner to postgres;

create table initial_project.employees
(
    id             integer generated by default as identity
        constraint id
            primary key,
    name           varchar,
    type_id        integer
        constraint employees_types_id_fk
            references types
            on update cascade on delete cascade,
    leave_id       integer
        constraint employees_leaves_id_fk
            references leaves,
    entity_info_id integer
        constraint employees_entity_info_id_fk
            references entity_info
);

alter table initial_project.employees
    owner to postgres;

create table initial_project.leave_requests
(
    id             integer generated by default as identity
        constraint leave_requests_pk
            primary key,
    employee_id    integer
        constraint leave_requests_employees_id_fk
            references employees
            on update cascade on delete cascade,
    approved       boolean,
    start_date     date not null,
    end_date       date not null,
    entity_info_id integer
        constraint leave_requests_entity_info_id_fk
            references entity_info
);

alter table initial_project.leave_requests
    owner to postgres;

